# Generated by Django 5.0.4 on 2024-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PAID", "PAID"),
                    ("EXPIRED", "EXPIRED"),
                ],
                max_length=10,
            ),
        ),
    ]
