# Generated by Django 5.0.4 on 2024-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
